-- describe("Neovim settings", function()
-- 	it("should have set the correct options", function()
-- 		-- Test if certain Neovim settings are correctly set
-- 		assert.are.equal(vim.opt.number:get(), true) -- Example setting
-- 	end)
-- end)
