name: CI Build

on:
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Lua
      uses: leafo/gh-actions-lua@v11
      with:
          luaVersion: '5.4.7'

    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            luarocks \
            neovim=0.11.0 \
            curl
          sudo luarocks install luacheck
          sudo luarocks install busted

    - name: check vim version
      run: nvim -v
      
    - name: Run make
      run: make
